"""empty message

Revision ID: 44ebb7d118a0
Revises: 7d5bcf3a9df0
Create Date: 2026-02-26 13:16:23.380680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44ebb7d118a0'
down_revision = '7d5bcf3a9df0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sistur_timebank_deductions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('deduction_type', sa.Enum('folga', 'pagamento', name='deductiontype'), nullable=False),
    sa.Column('minutos_abatidos', sa.Integer(), nullable=False),
    sa.Column('data_registro', sa.Date(), nullable=False),
    sa.Column('pagamento_valor', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('observacao', sa.String(length=500), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['funcionario_id'], ['sistur_funcionarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sistur_timebank_deductions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sistur_timebank_deductions_data_registro'), ['data_registro'], unique=False)
        batch_op.create_index(batch_op.f('ix_sistur_timebank_deductions_funcionario_id'), ['funcionario_id'], unique=False)

    with op.batch_alter_table('sistur_funcionarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banco_horas_acumulado', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sistur_funcionarios', schema=None) as batch_op:
        batch_op.drop_column('banco_horas_acumulado')

    with op.batch_alter_table('sistur_timebank_deductions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sistur_timebank_deductions_funcionario_id'))
        batch_op.drop_index(batch_op.f('ix_sistur_timebank_deductions_data_registro'))

    op.drop_table('sistur_timebank_deductions')
    # ### end Alembic commands ###
