"""Initial migration

Revision ID: 52a3e2238608
Revises: 
Create Date: 2026-02-25 08:57:19.431415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52a3e2238608'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sistur_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('sistur_role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('modulo', sa.String(length=50), nullable=False),
    sa.Column('acao', sa.String(length=50), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['sistur_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'modulo', 'acao', name='uq_role_modulo_acao')
    )
    with op.batch_alter_table('sistur_role_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sistur_role_permissions_role_id'), ['role_id'], unique=False)

    with op.batch_alter_table('sistur_funcionarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_sistur_funcionarios_role_id'), ['role_id'], unique=False)
        batch_op.create_foreign_key(None, 'sistur_roles', ['role_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sistur_funcionarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sistur_funcionarios_role_id'))
        batch_op.drop_column('role_id')

    with op.batch_alter_table('sistur_role_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sistur_role_permissions_role_id'))

    op.drop_table('sistur_role_permissions')
    op.drop_table('sistur_roles')
    # ### end Alembic commands ###
