"""Add sistur_system_settings table

Revision ID: 66adfe9e90d5
Revises: e6591127a3b9
Create Date: 2026-02-26 10:09:58.645381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66adfe9e90d5'
down_revision = 'e6591127a3b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sistur_system_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chave', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Text(), nullable=True),
    sa.Column('tipo', sa.Enum('bool', 'string', 'int', name='settingtype'), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sistur_system_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sistur_system_settings_chave'), ['chave'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sistur_system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sistur_system_settings_chave'))

    op.drop_table('sistur_system_settings')
    # ### end Alembic commands ###
