"""add tolerance_snapshot to TimeDay

Revision ID: 7d5bcf3a9df0
Revises: 66adfe9e90d5
Create Date: 2026-02-26 11:41:39.061734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d5bcf3a9df0'
down_revision = '66adfe9e90d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sistur_time_days', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tolerance_snapshot', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sistur_time_days', schema=None) as batch_op:
        batch_op.drop_column('tolerance_snapshot')

    # ### end Alembic commands ###
