"""add jornada_semanal to funcionarios

Revision ID: c7ad3fc0adab
Revises: 52a3e2238608
Create Date: 2026-02-25 10:00:10.142438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7ad3fc0adab'
down_revision = '52a3e2238608'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sistur_funcionarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jornada_semanal', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sistur_funcionarios', schema=None) as batch_op:
        batch_op.drop_column('jornada_semanal')

    # ### end Alembic commands ###
