"""Add Estoque and Restaurante models

Revision ID: e6591127a3b9
Revises: e97432af4613
Create Date: 2026-02-25 12:36:54.818522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6591127a3b9'
down_revision = 'e97432af4613'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sistur_categorias_produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('sistur_locais_armazenamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tipo', sa.Enum('almoxarifado', 'freezer', 'geladeira', 'prateleira', 'outro', name='tipolocal'), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['sistur_locais_armazenamento.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sistur_locais_armazenamento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sistur_locais_armazenamento_parent_id'), ['parent_id'], unique=False)

    op.create_table('sistur_unidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('simbolo', sa.String(length=10), nullable=False),
    sa.Column('tipo', sa.Enum('dimensional', 'unitaria', name='tipounidade'), nullable=False),
    sa.Column('is_sistema', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('simbolo')
    )
    op.create_table('sistur_produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('codigo_barras', sa.String(length=50), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('RAW', 'RESALE', 'MANUFACTURED', 'RESOURCE', name='tipoproduto'), nullable=False),
    sa.Column('unidade_base_id', sa.Integer(), nullable=True),
    sa.Column('resource_parent_id', sa.Integer(), nullable=True),
    sa.Column('conteudo_quantidade', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('conteudo_unidade_id', sa.Integer(), nullable=True),
    sa.Column('custo_medio', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('preco_venda', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('estoque_minimo', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('is_perecivel', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['sistur_categorias_produto.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conteudo_unidade_id'], ['sistur_unidades.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resource_parent_id'], ['sistur_produtos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unidade_base_id'], ['sistur_unidades.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    with op.batch_alter_table('sistur_produtos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sistur_produtos_categoria_id'), ['categoria_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sistur_produtos_nome'), ['nome'], unique=False)

    op.create_table('sistur_conversoes_unidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('de_unidade_id', sa.Integer(), nullable=False),
    sa.Column('para_unidade_id', sa.Integer(), nullable=False),
    sa.Column('fator', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['de_unidade_id'], ['sistur_unidades.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['para_unidade_id'], ['sistur_unidades.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['produto_id'], ['sistur_produtos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('produto_id', 'de_unidade_id', 'para_unidade_id', name='uq_conversao_produto_unidades')
    )
    with op.batch_alter_table('sistur_conversoes_unidade', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sistur_conversoes_unidade_produto_id'), ['produto_id'], unique=False)

    op.create_table('sistur_lotes_estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('codigo_lote', sa.String(length=100), nullable=True),
    sa.Column('local_aquisicao', sa.String(length=255), nullable=True),
    sa.Column('data_entrada', sa.DateTime(), nullable=False),
    sa.Column('data_fabricacao', sa.Date(), nullable=True),
    sa.Column('data_validade', sa.Date(), nullable=True),
    sa.Column('quantidade_inicial', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('custo_unitario', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('fornecedor_cnpj', sa.String(length=18), nullable=True),
    sa.Column('num_nfe', sa.String(length=50), nullable=True),
    sa.Column('chave_nfe', sa.String(length=44), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ativo', 'esgotado', 'vencido', 'bloqueado', name='statuslote'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['local_id'], ['sistur_locais_armazenamento.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['produto_id'], ['sistur_produtos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unidade_id'], ['sistur_unidades.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sistur_lotes_estoque', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sistur_lotes_estoque_local_id'), ['local_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sistur_lotes_estoque_produto_id'), ['produto_id'], unique=False)

    op.create_table('sistur_receitas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_pai_id', sa.Integer(), nullable=False),
    sa.Column('produto_filho_id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=True),
    sa.Column('quantidade_liquida', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('fator_rendimento', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('quantidade_bruta', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['produto_filho_id'], ['sistur_produtos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['produto_pai_id'], ['sistur_produtos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unidade_id'], ['sistur_unidades.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('produto_pai_id', 'produto_filho_id', name='uq_receita_pai_filho')
    )
    with op.batch_alter_table('sistur_receitas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sistur_receitas_produto_filho_id'), ['produto_filho_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sistur_receitas_produto_pai_id'), ['produto_pai_id'], unique=False)

    op.create_table('sistur_transacoes_estoque',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=True),
    sa.Column('de_local_id', sa.Integer(), nullable=True),
    sa.Column('para_local_id', sa.Integer(), nullable=True),
    sa.Column('funcionario_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('IN', 'OUT', 'SALE', 'LOSS', 'ADJUST', 'TRANSFER', name='tipotransacao'), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=True),
    sa.Column('custo_unitario', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('custo_total', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('referencia_tipo', sa.String(length=50), nullable=True),
    sa.Column('referencia_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['de_local_id'], ['sistur_locais_armazenamento.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lote_id'], ['sistur_lotes_estoque.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['para_local_id'], ['sistur_locais_armazenamento.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['produto_id'], ['sistur_produtos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unidade_id'], ['sistur_unidades.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sistur_transacoes_estoque', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sistur_transacoes_estoque_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_sistur_transacoes_estoque_funcionario_id'), ['funcionario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sistur_transacoes_estoque_lote_id'), ['lote_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sistur_transacoes_estoque_produto_id'), ['produto_id'], unique=False)

    op.create_table('sistur_perdas_estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=True),
    sa.Column('transacao_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('local_id', sa.Integer(), nullable=True),
    sa.Column('quantidade', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('motivo', sa.Enum('vencido', 'erro_producao', 'avariado', 'divergencia_inventario', 'outro', name='motivoperdaestoque'), nullable=False),
    sa.Column('detalhes_motivo', sa.Text(), nullable=True),
    sa.Column('custo_no_momento', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('valor_total_perda', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('funcionario_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['local_id'], ['sistur_locais_armazenamento.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lote_id'], ['sistur_lotes_estoque.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['produto_id'], ['sistur_produtos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transacao_id'], ['sistur_transacoes_estoque.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sistur_perdas_estoque', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sistur_perdas_estoque_produto_id'), ['produto_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sistur_perdas_estoque', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sistur_perdas_estoque_produto_id'))

    op.drop_table('sistur_perdas_estoque')
    with op.batch_alter_table('sistur_transacoes_estoque', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sistur_transacoes_estoque_produto_id'))
        batch_op.drop_index(batch_op.f('ix_sistur_transacoes_estoque_lote_id'))
        batch_op.drop_index(batch_op.f('ix_sistur_transacoes_estoque_funcionario_id'))
        batch_op.drop_index(batch_op.f('ix_sistur_transacoes_estoque_criado_em'))

    op.drop_table('sistur_transacoes_estoque')
    with op.batch_alter_table('sistur_receitas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sistur_receitas_produto_pai_id'))
        batch_op.drop_index(batch_op.f('ix_sistur_receitas_produto_filho_id'))

    op.drop_table('sistur_receitas')
    with op.batch_alter_table('sistur_lotes_estoque', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sistur_lotes_estoque_produto_id'))
        batch_op.drop_index(batch_op.f('ix_sistur_lotes_estoque_local_id'))

    op.drop_table('sistur_lotes_estoque')
    with op.batch_alter_table('sistur_conversoes_unidade', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sistur_conversoes_unidade_produto_id'))

    op.drop_table('sistur_conversoes_unidade')
    with op.batch_alter_table('sistur_produtos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sistur_produtos_nome'))
        batch_op.drop_index(batch_op.f('ix_sistur_produtos_categoria_id'))

    op.drop_table('sistur_produtos')
    op.drop_table('sistur_unidades')
    with op.batch_alter_table('sistur_locais_armazenamento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sistur_locais_armazenamento_parent_id'))

    op.drop_table('sistur_locais_armazenamento')
    op.drop_table('sistur_categorias_produto')
    # ### end Alembic commands ###
