"""add ponto tables: time_entries, time_days

Revision ID: e97432af4613
Revises: c7ad3fc0adab
Create Date: 2026-02-25 11:24:27.006505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e97432af4613'
down_revision = 'c7ad3fc0adab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sistur_time_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('minutos_trabalhados', sa.Integer(), nullable=False),
    sa.Column('saldo_calculado_minutos', sa.Integer(), nullable=False),
    sa.Column('saldo_final_minutos', sa.Integer(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('expected_minutes_snapshot', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['funcionario_id'], ['sistur_funcionarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('funcionario_id', 'shift_date', name='uq_funcionario_shift_date')
    )
    with op.batch_alter_table('sistur_time_days', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sistur_time_days_funcionario_id'), ['funcionario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sistur_time_days_shift_date'), ['shift_date'], unique=False)

    op.create_table('sistur_time_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('punch_time', sa.DateTime(), nullable=False),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('punch_type', sa.Enum('clock_in', 'lunch_start', 'lunch_end', 'clock_out', 'extra', name='punchtype'), nullable=False),
    sa.Column('source', sa.Enum('employee', 'admin', 'KIOSK', 'QR', name='punchsource'), nullable=False),
    sa.Column('processing_status', sa.Enum('PENDENTE', 'PROCESSADO', name='processingstatus'), nullable=False),
    sa.Column('admin_change_reason', sa.Text(), nullable=True),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['funcionario_id'], ['sistur_funcionarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sistur_time_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sistur_time_entries_funcionario_id'), ['funcionario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sistur_time_entries_punch_time'), ['punch_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_sistur_time_entries_shift_date'), ['shift_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sistur_time_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sistur_time_entries_shift_date'))
        batch_op.drop_index(batch_op.f('ix_sistur_time_entries_punch_time'))
        batch_op.drop_index(batch_op.f('ix_sistur_time_entries_funcionario_id'))

    op.drop_table('sistur_time_entries')
    with op.batch_alter_table('sistur_time_days', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sistur_time_days_shift_date'))
        batch_op.drop_index(batch_op.f('ix_sistur_time_days_funcionario_id'))

    op.drop_table('sistur_time_days')
    # ### end Alembic commands ###
